##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and RADIUSS
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

stages:
  - allocate_resources
  - build_and_test
  - release_resources

##############################################################################
# CORONA
# These are templates (.name) that can be included in other jobs to share part
# of the job definition.
.on_corona:
  tags:
    - shell
    - corona
  rules:
    # Runs except if we explicitly deactivate corona by variable.
    - if: '$ON_CORONA == "OFF"'
      when: never
    # Advanced jobs can only run on master, develop or if ALL_TARGETS is ON.
    # Set ADVANCED_JOB to ON in the job definition to make it an advanced job.
    - if: '$ADVANCED_JOB == "ON" && $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != "develop" && $ALL_TARGETS != "ON"'
      when: never
    # We should always release resources allocated in the pipeline.
    - if: '$CI_JOB_NAME =~ /release_resources/'
      when: always
    # A true statement is expected to allow jobs to run. Here is the default.
    - when: on_success

.build_and_test_on_corona:
  extends: [.custom_build_and_test, .on_corona]
  stage: build_and_test
  script:
    - echo ${ALLOC_NAME}
    - export JOBID=$(squeue -h --name=${ALLOC_NAME} --format=%A)
    - echo ${JOBID}
    - srun $( [[ -n "${JOBID}" ]] && echo "--jobid=${JOBID}" ) ${CORONA_BUILD_AND_TEST_JOB_ALLOC} scripts/gitlab/build_and_test.sh
  variables:
    SLURM_OVERLAP: 1

# In pre-build phase, allocate a node for builds.
allocate_resources (on corona):
  variables:
    GIT_STRATEGY: none
  extends: .on_corona
  stage: allocate_resources
  script:
    - salloc ${CORONA_BUILD_AND_TEST_SHARED_ALLOC} --no-shell --job-name=${ALLOC_NAME}

# In post-build phase, deallocate resources.
# Note : we make sure this is run even on build phase failure using a specific
# rule in the template ".on_corona".
release_resources (on corona):
  variables:
    GIT_STRATEGY: none
  extends: .on_corona
  stage: release_resources
  script:
    - export JOBID=$(squeue -h --name=${ALLOC_NAME} --format=%A)
    - ([[ -n "${JOBID}" ]] && scancel ${JOBID})
