##############################################################################
# Copyright (c) 2022, Lawrence Livermore National Security, LLC and RADIUSS
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

stages:
  - build_and_test

##############################################################################
# LASSEN
.on_lassen:
  variables:
  tags:
    - shell
    - lassen
  rules:
    - if: '$ON_LASSEN == "OFF"'
      when: never
    - if: '$ADVANCED_JOB == "ON" && $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != "develop" && $ALL_TARGETS != "ON"'
      when: never
    - when: on_success

.build_and_test_on_lassen:
  extends: [.custom_build_and_test, .on_lassen]
  stage: build_and_test
  script:
    - lalloc ${LASSEN_BUILD_AND_TEST_JOB_ALLOC} scripts/gitlab/build_and_test.sh

# Gitlab jobs for the lassen machine at LLNL.

# CPU only.
ibm_clang_9:
  variables:
    SPEC: "%clang@ibm.9.0.0"
  extends: .build_and_test_on_lassen

ibm_clang_9_gcc_8:
  variables:
    SPEC: "%clang@ibm.9.0.0 cxxflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\""
  extends: .build_and_test_on_lassen

gcc_8_3_1:
  variables:
    SPEC: "%gcc@8.3.1"
  extends: .build_and_test_on_lassen

pgi_20_4_gcc_8_3_1:
  variables:
    SPEC: "%pgi@20.4 cxxflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\""
  extends: .build_and_test_on_lassen

xl_16_1_1_10:
  variables:
    SPEC: "%xl@16.1.1.10"
  extends: .build_and_test_on_lassen

xl_16_1_1_10_gcc_8_3_1:
  variables:
    SPEC: "%xl@16.1.1.10 cxxflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\""
  extends: .build_and_test_on_lassen

# CUDA.
ibm_clang_9_gcc_8_cuda:
  variables:
    SPEC: "+cuda %clang@ibm.9.0.0 cxxflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 ^cuda@10.1.168\""
  extends: .build_and_test_on_lassen

xl_16_1_1_10_cuda:
  variables:
    SPEC: "+cuda %xl@16.1.1.10 cxxflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-7.3.1\" cflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-7.3.1 ^cuda@10.1.168 ^cmake@3.14.5\""
  extends: .build_and_test_on_lassen

xl_16_1_1_10_gcc_8_3_1_cuda_11:
  variables:
    SPEC: "+cuda tests=none %xl@16.1.1.10 cxxflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1\" cflags=\"--gcc-toolchain=/usr/tce/packages/gcc/gcc-8.3.1 ^cuda@11.0.2\""
  extends: .build_and_test_on_lassen
