##############################################################################
# Copyright (c) 2022-23, Lawrence Livermore National Security, LLC and RADIUSS
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

stages:
  - is-machine-up
  - status-initiate
  - jobs-stage-1
  - jobs-stage-2
  - jobs-stage-3
  - status-update

##############################################################################
# UTILITIES
.on_lassen:
  tags:
    - shell
    - lassen
  rules:
    # Runs except if we explicitly deactivate lassen by variable.
    - if: '$ON_LASSEN == "OFF"'
      when: never
    # Advanced jobs can only run on master, develop or if ALL_TARGETS is ON.
    # Set ADVANCED_JOB to ON in the job definition to make it an advanced job.
    - if: '$ADVANCED_JOB == "ON" && $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != "develop" && $ALL_TARGETS != "ON"'
      when: never
    # Only report failure if the pipeline failed.
    - if: '$CI_JOB_NAME =~ /status_failure/'
      when: on_failure
    # A true statement is expected to allow jobs to run. Here is the default.
    - when: on_success

.status_report: &status_report
    - export context="lassen"
    - |
      curl --url "https://api.github.com/repos/${GITHUB_PROJECT_ORG}/${GITHUB_PROJECT_NAME}/statuses/${CI_COMMIT_SHA}" \
           --header 'Content-Type: application/json' \
           --header "authorization: Bearer ${GITHUB_TOKEN}" \
           --data "{ \"state\": \"${pipeline_status}\", \"target_url\": \"${CI_PIPELINE_URL}\", \"description\": \"GitLab ${context} pipeline\", \"context\": \"ci/gitlab/${context}\" }"

.print_lassen_reproducer: &print_lassen_reproducer
    - |
      echo -e "\e[7;32m### Lassen reproducer\e[0m"
      if [[ -n "${LLNL_SERVICE_USER}" ]]; then echo -e "xsu ${LLNL_SERVICE_USER}"; fi
      echo -e "
      working_dir=\"/usr/workspace/\${USER}/${GITHUB_PROJECT_NAME}/${CI_PIPELINE_ID}-\$(date +%s)\"
      mkdir -p \${working_dir} && cd \${working_dir} \n
      git clone https://github.com/${GITHUB_PROJECT_ORG}/${GITHUB_PROJECT_NAME}.git --single-branch --depth=1 \n
      cd ${GITHUB_PROJECT_NAME}
      git fetch origin --depth=1 ${CI_COMMIT_SHA} \n
      git checkout ${CI_COMMIT_SHA} \n
      git submodule update --init --recursive \n
      SPEC=\"${SPEC//\"/\\\"}\" MODULE_LIST=\"${MODULE_LIST}\" lalloc ${LASSEN_JOB_ALLOC} ${JOB_CMD}"
      echo -e "\e[7;32m### End of reproducer\e[0m"

.job_on_lassen:
  extends: [.custom_job, .on_lassen]
  stage: jobs-stage-1
  script:
    # Print a reproducer
    - *print_lassen_reproducer
    # The actual launch command
    - lalloc ${LASSEN_JOB_ALLOC} ${JOB_CMD}

##############################################################################
# JOBS

status_pending:
  extends: [.on_lassen]
  variables:
    GIT_STRATEGY: none
  stage: status-initiate
  script:
    - export pipeline_status="pending"
    - *status_report

status_success:
  extends: [.on_lassen]
  variables:
    GIT_STRATEGY: none
  stage: status-update
  script:
    - export pipeline_status="success"
    - *status_report
  when: on_success

status_failure:
  extends: [.on_lassen]
  variables:
    GIT_STRATEGY: none
  stage: status-update
  script:
    - export pipeline_status="failure"
    - *status_report
  when: on_failure
