##############################################################################
# Copyright (c) 2022-23, Lawrence Livermore National Security, LLC and RADIUSS
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
##############################################################################

# Sets ID tokens for every job using `default:`
include:
  - project: 'lc-templates/id_tokens'
    file: 'id_tokens.yml'

stages:
  - is-machine-up
  - allocate-resources
  - jobs-stage-1
  - jobs-stage-2
  - jobs-stage-3
  - release-resources

##############################################################################
# UTILITIES
.on_ruby:
  tags:
    - shell
    - ruby
  rules:
    # Runs except if we explicitly deactivate ruby by variable.
    - if: '$ON_RUBY == "OFF"'
      when: never
    # Advanced jobs can only run on master, develop or if ALL_TARGETS is ON.
    # Set ADVANCED_JOB to ON in the job definition to make it an advanced job.
    - if: '$ADVANCED_JOB == "ON" && $CI_COMMIT_BRANCH != "main" && $CI_COMMIT_BRANCH != "develop" && $ALL_TARGETS != "ON"'
      when: never
    # We should always release resources allocated in the pipeline.
    - if: '$CI_JOB_NAME =~ /release_resources/'
      when: always
    # Only report failure if the pipeline failed.
    - if: '$CI_JOB_NAME =~ /status_failure/'
      when: on_failure
    # A true statement is expected to allow jobs to run. Here is the default.
    - when: on_success

.status_report: &status_report
    - export context="ruby"
    - |
      curl --url "https://api.github.com/repos/${GITHUB_PROJECT_ORG}/${GITHUB_PROJECT_NAME}/statuses/${CI_COMMIT_SHA}" \
           --header 'Content-Type: application/json' \
           --header "authorization: Bearer ${GITHUB_TOKEN}" \
           --data "{ \"state\": \"${pipeline_status}\", \"target_url\": \"${CI_PIPELINE_URL}\", \"description\": \"GitLab ${context} pipeline\", \"context\": \"ci/gitlab/${context}\" }"

.ruby_reproducer_init:
  script:
    - |
      echo -e "\e[7;32m### CI job ${CI_JOB_ID} reproducer on ruby (${SYS_TYPE}) \e[0m"
      if [[ -n "${LLNL_SERVICE_USER}" ]]; then echo -e "xsu ${LLNL_SERVICE_USER}"; fi
      echo -e "
      # Repository setup \n
      working_dir=\"/usr/workspace/\${USER}/${GITHUB_PROJECT_NAME}/${CI_JOB_ID}-\$(date +%s)\" \n
      mkdir -p \${working_dir} && cd \${working_dir} \n
      git clone https://github.com/${GITHUB_PROJECT_ORG}/${GITHUB_PROJECT_NAME}.git --single-branch --depth=1 \n
      cd ${GITHUB_PROJECT_NAME} \n
      git fetch origin --depth=1 ${CI_COMMIT_SHA} \n
      git checkout ${CI_COMMIT_SHA} \n
      git submodule update --init --recursive \n"

# We require project to define their job command using a variable (JOB_CMD).
# In customization/gitlab-ci.yml, we encourage to define this variable as
# non-expandable, so that project can use nested variables to configure the job
# command. The caveat is that the reproducer here cannot capture the
# definition of these variables in a generic fashion. By overriding the
# following section, projects can specify the variables to define in the
# reproducer to exactly reproduce the CI build.
.ruby_reproducer_vars:
  script:
    - |
      echo -e "# Define project specific variables here if any."
      #echo -e "export <CUSTOM_VAR>=\"${<CUSTOM_VAR>}\""

.ruby_reproducer_job:
  script:
    - |
      echo -e "srun ${RUBY_JOB_ALLOC} ${JOB_CMD}"
      echo -e "\e[7;32m### End of reproducer\e[0m"

.ruby_job_command:
  script:
    - srun $( [[ -n "${JOBID}" ]] && echo "--jobid=${JOBID}" ) ${RUBY_JOB_ALLOC} ${JOB_CMD}

.job_on_ruby:
  extends: [.custom_job, .on_ruby]
  stage: jobs-stage-1
  script:
    # Allocation information
    - echo -e "### Allocation name is ${ALLOC_NAME}"
    - export JOBID=$(squeue -h --name=${ALLOC_NAME} --format=%A)
    - echo -e "### Job ID is ${JOBID}"
    # Print a reproducer
    - !reference [.ruby_reproducer_init, script]
    - !reference [.ruby_reproducer_vars, script]
    - !reference [.ruby_reproducer_job, script]
    # The actual launch command
    - !reference [.ruby_job_command, script]

##############################################################################
# JOBS

# In pre-build phase, allocate a node for builds.
# TODO: make the resource configurable, not all projects will want the same.
allocate_resources:
  variables:
    GIT_STRATEGY: none
  extends: .on_ruby
  stage: allocate-resources
  script:
    - salloc ${RUBY_SHARED_ALLOC} --no-shell --job-name=${ALLOC_NAME}

status_pending:
  extends: [.on_ruby]
  variables:
    GIT_STRATEGY: none
  stage: allocate-resources
  script:
    - export pipeline_status="pending"
    - *status_report

# In post-build phase, deallocate resources.
# Note : we make sure this is run even on build phase failure using a specific
# rule in the template ".on_ruby".
release_resources:
  variables:
    GIT_STRATEGY: none
  extends: .on_ruby
  stage: release-resources
  script:
    - export JOBID=$(squeue -h --name=${ALLOC_NAME} --format=%A)
    - ([[ -n "${JOBID}" ]] && scancel ${JOBID} || exit 0)

status_success:
  extends: [.on_ruby]
  variables:
    GIT_STRATEGY: none
  stage: release-resources
  script:
    - export pipeline_status="success"
    - *status_report
  when: on_success

status_failure:
  extends: [.on_ruby]
  variables:
    GIT_STRATEGY: none
  stage: release-resources
  script:
    - export pipeline_status="failure"
    - *status_report
  when: on_failure
