###############################################################################
# Copyright (c) 2022-25, Lawrence Livermore National Security, LLC and RADIUSS
# project contributors. See the COPYRIGHT file for details.
#
# SPDX-License-Identifier: (MIT)
###############################################################################

# Example .gitlab-ci.yml for consuming projects using GitLab CI Components
#
# This file demonstrates how to use the RADIUSS Shared CI components instead
# of the legacy include-based approach.
#
# MIGRATION: This replaces the customization/gitlab-ci.yml template

###############################################################################
# STAGES
###############################################################################
# IMPORTANT: You must define stages yourself to allow customization.
# The following stages are REQUIRED by RADIUSS Shared CI components:

stages:
  - prerequisites           # Required: machine availability checks
  - build-and-test          # Required: build and test jobs
  - performance-measurements # Required: if using performance pipeline
  # Add your custom stages here:
  # - custom-stage-1
  # - custom-stage-2

###############################################################################
# VARIABLES
###############################################################################

variables:
  # Service user configuration
  LLNL_SERVICE_USER: ""  # Set to your service user if using one

  # GitHub integration (required for status reporting)
  GITHUB_PROJECT_NAME: "my-project"
  GITHUB_PROJECT_ORG: "LLNL"
  # GITHUB_TOKEN should be set as a CI/CD variable in GitLab settings

  # Build configuration
  GIT_SUBMODULE_STRATEGY: recursive

  # Job command - use non-expandable variables for flexibility
  JOB_CMD:
    value: "./scripts/build-and-test.sh"
    expand: false

  # Component version to use
  RADIUSS_SHARED_CI_REF: "v2025.10.0"

###############################################################################
# INCLUDES
###############################################################################

include:
  # Base pipeline templates and utilities
  - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/base-pipeline@v2025.10.0
    inputs:
      github_project_name: $GITHUB_PROJECT_NAME
      github_project_org: $GITHUB_PROJECT_ORG
      github_token: $GITHUB_TOKEN
      component_version: $RADIUSS_SHARED_CI_REF

  # Optional: Draft PR filter
  - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/utility-draft-pr-filter@v2025.10.0
    inputs:
      github_token: $GITHUB_TOKEN
      github_project_name: $GITHUB_PROJECT_NAME
      github_project_org: $GITHUB_PROJECT_ORG

  # Local variables (used for component inputs and forwarded to child pipelines)
  - local: '.gitlab/custom-variables.yml'

###############################################################################
# MACHINE PIPELINES
###############################################################################

# Dane (SLURM-based)
dane-up-check:
  variables:
    CI_MACHINE: "dane"
  extends: [.machine-check]
  rules:
    - if: '$ON_DANE == "OFF"'
      when: never
    - when: on_success

dane-build-and-test:
  variables:
    CI_MACHINE: "dane"
  needs: [dane-up-check]
  extends: [.build-and-test]
  rules:
    - if: '$ON_DANE == "OFF"'
      when: never
    - when: on_success
  trigger:
    include:
      - local: '.gitlab/custom-jobs.yml'
      - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/dane-pipeline@v2025.10.0
        inputs:
          job_cmd: $JOB_CMD
          shared_alloc: $DANE_SHARED_ALLOC
          job_alloc: $DANE_JOB_ALLOC
          github_project_name: $GITHUB_PROJECT_NAME
          github_project_org: $GITHUB_PROJECT_ORG
      - local: '.gitlab/jobs/dane.yml'

# Lassen (LSF-based)
lassen-up-check:
  variables:
    CI_MACHINE: "lassen"
  extends: [.machine-check]
  rules:
    - if: '$ON_LASSEN == "OFF"'
      when: never
    - when: on_success

lassen-build-and-test:
  variables:
    CI_MACHINE: "lassen"
  needs: [lassen-up-check]
  extends: [.build-and-test]
  rules:
    - if: '$ON_LASSEN == "OFF"'
      when: never
    - when: on_success
  trigger:
    include:
      - local: '.gitlab/custom-jobs.yml'
      - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/lassen-pipeline@v2025.10.0
        inputs:
          job_cmd: $JOB_CMD
          job_alloc: $LASSEN_JOB_ALLOC
          github_project_name: $GITHUB_PROJECT_NAME
          github_project_org: $GITHUB_PROJECT_ORG
      - local: '.gitlab/jobs/lassen.yml'

# Corona (flux-based)
corona-up-check:
  variables:
    CI_MACHINE: "corona"
  extends: [.machine-check]
  rules:
    - if: '$ON_CORONA == "OFF"'
      when: never
    - when: on_success

corona-build-and-test:
  variables:
    CI_MACHINE: "corona"
  needs: [corona-up-check]
  extends: [.build-and-test]
  rules:
    - if: '$ON_CORONA == "OFF"'
      when: never
    - when: on_success
  trigger:
    include:
      - local: '.gitlab/custom-jobs.yml'
      - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/corona-pipeline@v2025.10.0
        inputs:
          job_cmd: $JOB_CMD
          shared_alloc: $CORONA_SHARED_ALLOC
          job_alloc: $CORONA_JOB_ALLOC
          github_project_name: $GITHUB_PROJECT_NAME
          github_project_org: $GITHUB_PROJECT_ORG
      - local: '.gitlab/jobs/corona.yml'

# Add similar blocks for: matrix, tioga, tuolumne
# (See full template for all machines)

###############################################################################
# PERFORMANCE PIPELINE (Optional)
###############################################################################

performance-measurements:
  stage: performance-measurements
  rules:
    # Add conditions for when to run performance tests
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'
      when: on_success
    - when: manual
  trigger:
    include:
      - local: '.gitlab/custom-jobs.yml'
      - component: $CI_SERVER_FQDN/radiuss/radiuss-shared-ci/performance-pipeline@v2025.10.0
        inputs:
          job_cmd: "./scripts/run-benchmarks.sh"
          github_token: $GITHUB_TOKEN
          github_project_name: $GITHUB_PROJECT_NAME
          github_project_org: $GITHUB_PROJECT_ORG
      - local: '.gitlab/jobs/performances.yml'
